### ISSUE TITLE
Merge keystore into link?

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-keystore#10]
Now that there is no more registry to depend on radicle-keystore, should we merge it into the `radicle-link` repo?

/cc @kim @xla @FintanH

**Comment by xla** [comment]
Woohoo, we've come full circle! As long as we don't depend on published crates, one monorepo pinned at a single sha is the simplest to handle for downstream. Yet it didn't cause any trouble recently, so no strong preference.

**Comment by FintanH** [comment]
I don't see a need for us to take on that work, to be honest.

> As long as we don't depend on published crates,

So maybe we can publish this crate since it's pretty stable at the moment? It can join `radicle-surf` in Crate Olympus

**Comment by kim** [comment]
I can't make myself enthused about a monorepo, unless we would also employ a
build system which is designed for this kind of thing. Given the current
situation (lock files, workspaces not truly isolating, incrementalism got a long
way to go), it's just not going to work.

And I'm not even talking about the lower incentives to create proper abstraction
boundaries.

**Comment by kim** [comment]
Keep in mind also that this crate is potentially going to create executables,
the link times of which you'd have to pay for.

**Comment by cloudhead** [comment]
Ok, I’m fine with keeping as-is, though I think it would have made it easier to do atomic changes across crates.

Is the build process fundamentally different when crates are in the same workspace, vs not? (Not that we’d be obliged to add it to the workspace)

**Comment by cloudhead** [comment]
Note that my proposal is about moving the crate to the radicle-link repo, *not* merging the code into librad.

**Comment by kim** [comment]
I'm not sure this is the right place to discuss how monorepos only work with
specialised tooling. My point stands: cargo is painful enough already, and I'd
rather split off more stuff into smaller repos.

If you care about monorepos, please open an RFC on radicle-decisions.

This will have to detail how we agree on questions of process, releases,
non-linear development, builds, and tooling. We will need to reach for bazel or
something comparable, so resources must be allocated to architect and implement
the build pipeline.

**Comment by cloudhead** [comment]
Okay, this seems controversial, closing :+1:
